- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_SEA_0AAD2DF1E }}
    action: "upload"
    app_location: "/" # Where your HTML file is located
    api_location: "" # No API, leave empty
    output_location: "" # Leave empty when skipping build
    skip_app_build: true # This tells Azure to skip the build process
    github_id_token: ${{ steps.idtoken.outputs.result }}
